<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.8 setup script
 * Date: Tue, 22 Oct 2013 15:50:26 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: info2 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'servinfo-db';
$cfg['Servers'][$i]['host'] = 'servinfo-db';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowRoot'] = false;
$cfg['Servers'][$i]['DisableIS'] = false;

/* End of servers configuration */

$cfg['blowfish_secret'] = '5266827cea7110.07990257';
$cfg['DefaultLang'] = 'fr';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>